name: Test Email Action

on:
  push:    # Runs on every push to the main branch
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f1001876@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
